# Generated by Django 6.0.5 on 2026-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('book_type', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('book_quantity', models.IntegerField()),
            ],
        ),
    ]
